<?php
// hash_gen.php
require_once 'config/database.php';

$password = 'admin123';
$hashed_password = password_hash($password, PASSWORD_DEFAULT);

try {
    // This updates the existing 'admin' user with a fresh hash generated by YOUR server
    $stmt = $pdo->prepare("UPDATE users SET password = ? WHERE username = 'admin'");
    $stmt->execute([$hashed_password]);

    echo "Success! The password for 'admin' has been reset to: admin123<br>";
    echo "New Hash stored: " . $hashed_password;
} catch (Exception $e) {
    echo "Error: " . $e->getMessage();
}
