-- Insert Members in Smaller Batches
-- Run this in MySQL Workbench to add all 212 members
USE attendance_system;

-- Batch 1: First 50 members
INSERT INTO members (name, email, phone, gender, location, occupation, congregation_group, baptized, status, date_joined) VALUES
('Lord William', NULL, '240279748', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Frederica Afful', NULL, '272432100', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Michael Abia Sackey', NULL, '243493595', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Sara Ntow', NULL, '262440603', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Martey Naomi', NULL, '243202612', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('John Richard', NULL, '239102664', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Edem Affram', NULL, '244680038', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Vivian Andokow', NULL, '279639585', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Bennita Sobeli', NULL, '201859341', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Vera Selorm Tasiame', NULL, '506946794', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Benedicta Banahene', NULL, '506794254', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Wisdom Dodzi Melio', NULL, '241563715', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Agbottah Mawuli', NULL, '249352407', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Asafo Adjei Michael', NULL, '509601099', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Obikyenbi Norah Mawulawoe', NULL, '545398015', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Nandy Amelley', NULL, '240645308', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Issaka Salomey', NULL, '240036642', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Eric Baidoo', NULL, '243838490', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Princelove Okyere', NULL, '506703468', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Derrick Kwasi Frimpong', NULL, '208026225', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Henry Shadeko', NULL, '547218101', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Nana Kwesi AduBoahen', NULL, '552001917', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Bernice Kumah', NULL, '542329937', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Gloria Agyekum', NULL, '206462476', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Samuel Nunoo', NULL, '545333330', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Elizabeth Esenam', NULL, '545560957', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Doris Inkoom', NULL, '553829520', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Sedor Wisdom', NULL, '599610238', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('John Richard', NULL, '504843020', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Akpandja Abrampa', NULL, '544979407', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Joshua Adusu', NULL, '546109539', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('LP Rukaya', NULL, '249317707', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Lady Wendy', NULL, '244684663', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('KINGSLEY SAKYI BUDU', NULL, '270231629', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Aryee Isaac', NULL, '598034778', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Naa Akushika Allotey', NULL, '208060082', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Stephen Tawiah', NULL, '545577055', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Pastor Andrews', NULL, '244984221', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Rev David Ampah korsah', NULL, '244697701', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Abigail Darko', NULL, '244950338', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Adepa Priscilla', NULL, '249390618', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Blessing Issifu', NULL, '543273329', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Michael kissi Nyarko', NULL, '579093844', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Jessica Xedudzi', NULL, '596444979', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Gifty Cudjoe', NULL, '249239248', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Korley David', NULL, '249255978', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Adjei-Adomako George', NULL, '276115331', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Apedo Joshua', NULL, '543075773', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Kojo Agyapong Ofori', NULL, '543397273', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE()),
('Abigail Adetona', NULL, '554666470', NULL, NULL, NULL, 'Adult', 'no', 'active', CURDATE());

SELECT 'Batch 1 completed - 50 members added' as status;
SELECT COUNT(*) as current_total FROM members;